### ISSUE TITLE
Scripts in postgresql-start are not taken into account if they are symbolic links

### ISSUE THREAD

**Issue by adest** [sclorg/postgresql-container#350] opened 2019-11-08 15:43 UTC
Hello,

We use OKD 3.11

So we mount sh scripts with config map (the okd way to provide configuration files to containers) under `/opt/app-root/src/postgresql-start` folder.
These config maps "files" are provided as symbolic links.
ex:
```
sh-4.2$ cd /opt/app-root/src/postgresql-start
sh-4.2$ ls -l
total 0
lrwxrwxrwx 1 root root 20 Nov  7 15:06 createuser.sh -> ..data/createuser.sh
```

The script is well provisioned with docker-compose but does not work with okd.

After some investigations, we remarked that the function `get_matched_files ()` in `src/root/usr/share/container-scripts/postgresql/common.sh` 
only list file with the following command `find "$dir" -maxdepth 1 -type f -name "$pattern" -printf "%f\n"` (-type f limits find to files and not symbolic links).

Can you make this script compliant with symbolic links please ?
It would be very handy for okd or openshift deployment.

**Comment by pkubatrh** [comment] 2019-11-11 07:46
Hi @adest, thanks for the issue!

This looks like a duplicate of #325 so I will be closing this one, but will take a look at getting the scripts to work with config maps.

**Closed by pkubatrh** 2019-11-11 07:46 UTC
